services:

  coupon.api:
    container_name: coupon.api
    hostname: coupon.api
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      DATABASE_HOST: coupon.postgres
    ports:
      - "8080:8080"
    networks:
      - coupon-network
    depends_on:
      coupon.postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: unless-stopped


  coupon.postgres:
    env_file: .env
    image: postgres:18
    container_name: coupon.postgres
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - coupon-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  coupon-network:

volumes:
  postgres_data:
